import argparse

def get_args():
    parser = argparse.ArgumentParser(
        prog="pairwiseANIviz",
        description="Pairwise ANI(Average Nucleotide Identity) visulization tool.",
        usage='%(prog)s [options]',
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=
        "General usage\n----------------\n"
        "ANI result visulization without classification info:\n"
        "   $ pairwiseANIviz ani_result.txt\n\n"
        "ANI result visulization with classification info:\n"
        "   $ pairwiseANIviz ani_result.txt --classificationFile classification_result.tsv\n\n"
        "Runjia Ji, 2023"
    )

    parser.add_argument('-v', '--version', action='version', version='%(prog)s 0.1', help='Show pairwiseANIviz version number and exit.')
    parser.add_argument('anifile', type=str, help='File containing pairwise ANI analysis result.')
    parser.add_argument('-o', '--outdir', type=str, help="Directory to save the output figures (defaults 'pairwiseANIviz').")
    parser.add_argument('--method', type=str, choices=['single', 'complete', 'average', 'weighted', 'centroid', 'median', 'ward'], 
                        help="Linkage method to use for calculating clusters (default 'average').\n See https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html#scipy.cluster.hierarchy.linkage")
    parser.add_argument('--metric', type=str, 
                        choices=[
                        'braycurtis', 'canberra', 'chebyshev', 'cityblock', 'correlation', 'cosine', 'dice', 'euclidean', 'hamming', 'jaccard', 'jensenshannon', 'kulczynski1', 'mahalanobis', 'matching', 'minkowski', 'rogerstanimoto', 'russellrao', 'seuclidean', 'sokalmichener', 'sokalsneath', 'sqeuclidean', 'yule'
                        ],
                        help="The distance metric to use (default 'euclidean').\n See https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html#scipy.spatial.distance.pdist"
                    )
    parser.add_argument('-cmap', '--colormap', type=str, help="Matplotlib colormap used when drawing the heatmap of ANI values (default 'Blues').")
    parser.add_argument('-w', '--figWidth', type=int, help="Figure width (default '15').")
    parser.add_argument('-h', '--figHeight', type=int, help="Figure height (default '15').")
    parser.add_argument('--linewidth', type=float, help="Line width of the main heatmap (default 0.5)")
    parser.add_argument('--linecolor', type=str, help="Line color of the main heatmap (default 'grey').")
    parser.add_argument('--rowCluster', help="Draw the row cluster.", action='store_true')
    parser.add_argument('--colCluster', help="Draw the column cluster.", action='store_true')
    parser.add_argument('--annotation', help="Show ANI values on the plot.", action='store_true')

    parser.add_argument('-c', '--classificationFile', type=str, help='File containing classification result generated by GTDBTk(https://github.com/Ecogenomics/GTDBTk).')
    parser.add_argument('-t', '--taxaLevel', type=str, choices=['domain', 'phylum', 'class', 'order', 'family', 'genus', 'species'], help='Taxa level illustrated on the plot.\n Choose from "domain, phylum, class, order, family, genus, species".\n Note that this parameter only works if classification result was input.')
    parser.add_argument('--colorPalette', type=str, help="Color palette used to return a specified number of evenly spaced hues which are then used to illustrate different taxa (default 'hls').\n Note that this parameter only works if classification result was input.")
    

    args = parser.parse_args()
    return args
